# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_final.ui'
#
# Created by: PyQt5 UI code generator 5.10.1

# Definizione degli elementi dell'interfaccia
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(678, 721)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(53, 130, 581, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_choose_image = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_choose_image.setObjectName("label_choose_image")
        self.horizontalLayout.addWidget(self.label_choose_image)
        self.text_choose_image = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.text_choose_image.setObjectName("text_choose_image")
        self.horizontalLayout.addWidget(self.text_choose_image)
        self.button_browse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_browse.setObjectName("button_browse")
        self.horizontalLayout.addWidget(self.button_browse)
        self.progress_bar = QtWidgets.QProgressBar(Widget)
        self.progress_bar.setGeometry(QtCore.QRect(96, 400, 491, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 340, 251, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_compute_dct = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_compute_dct.setObjectName("button_compute_dct")
        self.horizontalLayout_2.addWidget(self.button_compute_dct)
        self.check_box_save_images = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.check_box_save_images.setObjectName("check_box_save_images")
        self.horizontalLayout_2.addWidget(self.check_box_save_images)
        self.label_load_image = QtWidgets.QLabel(Widget)
        self.label_load_image.setGeometry(QtCore.QRect(51, 89, 80, 16))
        self.label_load_image.setFixedHeight(20)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_load_image.setFont(font)
        self.label_load_image.setObjectName("label_load_image")
        self.line_8 = QtWidgets.QFrame(Widget)
        self.line_8.setGeometry(QtCore.QRect(20, 90, 31, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Widget)
        self.line_9.setGeometry(QtCore.QRect(129, 91, 531, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.text_log = QtWidgets.QTextBrowser(Widget)
        self.text_log.setGeometry(QtCore.QRect(50, 570, 581, 101))
        self.text_log.setObjectName("text_log")
        self.button_show_comparison = QtWidgets.QPushButton(Widget)
        self.button_show_comparison.setGeometry(QtCore.QRect(170, 480, 161, 32))
        self.button_show_comparison.setObjectName("button_show_comparison")
        self.label_show_difference = QtWidgets.QPushButton(Widget)
        self.label_show_difference.setGeometry(QtCore.QRect(350, 480, 161, 31))
        self.label_show_difference.setObjectName("label_show_difference")
        self.label_settings = QtWidgets.QLabel(Widget)
        self.label_settings.setGeometry(QtCore.QRect(53, 188, 71, 16))
        self.label_settings.setFixedHeight(20)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_settings.setFont(font)
        self.label_settings.setObjectName("label_settings")
        self.line_13 = QtWidgets.QFrame(Widget)
        self.line_13.setGeometry(QtCore.QRect(20, 190, 31, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Widget)
        self.line_14.setGeometry(QtCore.QRect(108, 190, 553, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_processing = QtWidgets.QLabel(Widget)
        self.label_processing.setGeometry(QtCore.QRect(53, 298, 71, 16))
        self.label_processing.setFixedHeight(20)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_processing.setFont(font)
        self.label_processing.setObjectName("label_processing")
        self.line_12 = QtWidgets.QFrame(Widget)
        self.line_12.setGeometry(QtCore.QRect(20, 300, 31, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_15 = QtWidgets.QFrame(Widget)
        self.line_15.setGeometry(QtCore.QRect(128, 300, 534, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_visualization = QtWidgets.QLabel(Widget)
        self.label_visualization.setGeometry(QtCore.QRect(53, 441, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_visualization.setFont(font)
        self.label_visualization.setObjectName("label_visualization")
        self.line_16 = QtWidgets.QFrame(Widget)
        self.line_16.setGeometry(QtCore.QRect(20, 440, 31, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(Widget)
        self.line_17.setGeometry(QtCore.QRect(134, 440, 527, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_log = QtWidgets.QLabel(Widget)
        self.label_log.setGeometry(QtCore.QRect(53, 527, 71, 16))
        self.label_log.setFixedHeight(20)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.label_log.setFont(font)
        self.label_log.setObjectName("label_log")
        self.line_18 = QtWidgets.QFrame(Widget)
        self.line_18.setGeometry(QtCore.QRect(20, 529, 31, 20))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(Widget)
        self.line_19.setGeometry(QtCore.QRect(85, 529, 577, 20))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.label_max_value = QtWidgets.QLabel(Widget)
        self.label_max_value.setGeometry(QtCore.QRect(400, 272, 150, 16))
        self.label_max_value.setObjectName("label_max_value")
        self.authors = QtWidgets.QLabel(Widget)
        #self.authors.setGeometry(QtCore.QRect(380, 75, 311, 20))
        self.authors.setGeometry(QtCore.QRect(300, 75, 400, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.authors.setFont(font)
        self.authors.setObjectName("authors")
        self.title = QtWidgets.QLabel(Widget)
        #self.title.setGeometry(QtCore.QRect(148, 10, 451, 78))
        #Modificato per non tagliare il titolo
        self.title.setGeometry(QtCore.QRect(180, 10, 600, 78))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(180, 210, 211, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(5, 11, 5, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_set_par_b = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_set_par_b.setObjectName("label_set_par_b")
        self.horizontalLayout_4.addWidget(self.label_set_par_b)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.doubleSpinBox_2.setDecimals(2)
        self.doubleSpinBox_2.setMaximum(10000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(180, 258, 211, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(5, 11, 5, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_set_parameter_d = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_set_parameter_d.setObjectName("label_set_parameter_d")
        self.horizontalLayout_5.addWidget(self.label_set_parameter_d)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.doubleSpinBox_3.setDecimals(2)
        self.doubleSpinBox_3.setMaximum(10000.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_3)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "DCT Image Compression"))
        self.label_choose_image.setText(_translate("Widget", "Choose image:"))
        self.button_browse.setText(_translate("Widget", "Browse..."))
        self.button_compute_dct.setText(_translate("Widget", "Compute DCT"))
        self.check_box_save_images.setText(_translate("Widget", "Save images"))
        self.label_load_image.setText(_translate("Widget", "Load image"))
        self.button_show_comparison.setText(_translate("Widget", "Show comparison"))
        self.label_show_difference.setText(_translate("Widget", "Show difference"))
        self.label_settings.setText(_translate("Widget", "Settings"))
        self.label_processing.setText(_translate("Widget", "Processing"))
        self.label_visualization.setText(_translate("Widget", "Visualization"))
        self.label_log.setText(_translate("Widget", "Log"))
        self.label_max_value.setText(_translate("Widget", "Max value: 5030"))
        self.authors.setText(_translate("Widget", "Lucrezia Patruno 795281, Federico Pozzi 794281"))
        self.title.setText(_translate("Widget", "DCT Image Compression"))
        self.label_set_par_b.setText(_translate("Widget", "Set parameter b:"))
        self.label_set_parameter_d.setText(_translate("Widget", "Set parameter d:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myfirstGUI = QtWidgets.QDialog()
    ui = Ui_Widget()
    ui.setupUi(myfirstGUI)
    myfirstGUI.show()
    sys.exit(app.exec_())