#!/usr/bin/env python
import matplotlib

matplotlib.use("Qt4Agg")

from sh_gui import Ui_Dialog
from PyQt5 import QtWidgets
import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()

    prog = Ui_Dialog()
    prog.setupUi(dialog)

    dialog.show()
    sys.exit(app.exec_())
